import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.css';
import { NavbarWithRightCta } from '../components/NavbarWithRightCta/NavbarWithRightCta';
import { BlogWithTile } from '../components/BlogWithTile/BlogWithTile';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <NavbarWithRightCta />
            <main className={styles.main}>
                <BlogWithTile />
            </main>
        </div>
    );
};

export default Home;
